### ISSUE TITLE
Additional Sorting Algorithms

### ISSUE THREAD

**Issue by KieranP** [sadanandpai/sorting-visualizer#1]
Thank you for this visualisation. Really great work :-)

Would be nice to see the following represented also:

https://en.wikipedia.org/wiki/Comb_sort (improved on Bubble sort)
https://en.wikipedia.org/wiki/Shellsort (improves on Insertion sort)
https://en.wikipedia.org/wiki/Introsort (hybrid Quicksort/Heapsort)
https://en.wikipedia.org/wiki/Timsort (hybrid Mergesort/InsertionSort)
https://en.wikipedia.org/wiki/Block_sort
https://en.wikipedia.org/wiki/Bucket_sort
https://en.wikipedia.org/wiki/Radix_sort

**Comment by sadanandpai** [comment]
Thanks for the suggestion @KieranP 
This can be surely considered in future development
