### ISSUE TITLE
BUG: site not loading on github pages

### ISSUE THREAD

**Issue by honeybhardwaj** [sadanandpai/sorting-visualizer#2]
**Describe the bug**
the site isn't loading in the browser using the github page link.

**Screenshots**
![Screenshot from 2021-06-21 17-22-11](https://user-images.githubusercontent.com/51120790/122757430-3da3f180-d2b5-11eb-9f36-cca6c68eeb07.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: Chrome

**Comment by sadanandpai** [comment]
@honeybhardwaj Thanks for reporting. Can you please attach the developer tools > console screenshot to check the errors.

**Comment by honeybhardwaj** [comment]
> @honeybhardwaj It looks like the url is incorrect.
> Try the below link
> https://sadanandpai.github.io/sorting-visualizer/dist/

yeah its working great work !!! what all tech you used??

**Comment by sadanandpai** [comment]
Please go through the readme file. I have mentioned everything.
https://github.com/sadanandpai/sorting-visualizer/blob/main/README.md
