### ISSUE TITLE
Problems after switching to react 18

### ISSUE THREAD

**Issue by KrzysztofCelebak** [sadanandpai/sorting-visualizer#3]
Hi, thank you for this visualization.

After upgrading to react 18 and enabling Strict mode the animations stops working do you have any suggestions how to fix that?

**Comment by sadanandpai** [comment]
I need to look into it

**Comment by KrzysztofCelebak** [comment]
siktir lan, Zamanında düzeltmedin ve tezimi savunmadım, şimdi sıçtım 😡😡😡🥶🥶🥶

**Comment by sadanandpai** [comment]
@KrzysztofCelebak i was occupied with the other work. There is a good amount of time to be spent here w. R. T react and material. Not planning to pick this for now
