### ISSUE TITLE
display and highlight the algorithm

### ISSUE THREAD

**Issue by VarshaSubramanya** [sadanandpai/sorting-visualizer#4]
Hi, thank you for building this visualization tool.
Is there any possibility adding an extra feature of displaying the algorithm/code and highlighting the lines as they are executed apart from the visualization of the algorithm?

**Comment by sadanandpai** [comment]
hi @VarshaSubramanya , I have never thought about that while building. That might be a great addition. I don't have plans to work on this repo as of now. PRs are welcome.

**Comment by KrzysztofCelebak** [comment]
siktir lan, Zamanında düzeltmedin ve tezimi savunmadım, **şimdi sıçtım** 😡😡😡🥶🥶🥶
